#!/bin/sh

set -e

DIR="$(dirname "$0")"
ABSDIR="$(realpath "$DIR")"

# Build, and show output. (Otherwise the user won't see progress on slow steps)
docker build "$DIR" --target=development

IMAGE_ID="$(docker build -q "$DIR" --target=development)"

exec docker run --rm -it \
  --network overviewserver_default \
  --volume "$ABSDIR"/assets:/app/assets:ro \
  --volume "$ABSDIR"/config:/app/config:ro \
  --volume "$ABSDIR"/generator:/app/generator:ro \
  --volume "$ABSDIR"/views:/app/views:ro \
  $EXTRA_DOCKER_RUN_ARGS \
  $IMAGE_ID "$@"
