#!/bin/sh

DIR="$(dirname "$0")"
ABSDIR="$(realpath "$DIR")"

set -e

. "$DIR"/config

IMAGE_NAME=overview/overview-integration-tester:$OVERVIEW_INTEGRATION_TESTER_VERSION
docker image ls -q $IMAGE_NAME >/dev/null || docker pull $IMAGE_NAME

exec docker run --rm -it \
  --network ${DEVELOPMENT_PROJECT_NAME}_default \
  -e OVERVIEW_URL=http://overview-web \
  -e WAIT_FOR_URLS="$WAIT_FOR_URLS" \
  -e HEADLESS=true \
  -v "$ABSDIR"/files:/app/files \
  -v "$ABSDIR"/helpers:/app/helpers \
  -v "$ABSDIR"/reports:/app/reports \
  -v "$ABSDIR"/spec:/app/spec \
  "$IMAGE_NAME" "$@"
